# NUMPY

In [ ]:
import numpy as np

In [4]:
# creation of a two dimention matrix using ranndom ranmbers from 1,100.

import numpy as np
two_dim=np.random.randint(1,100,16).reshape(4,4)
two_dim

array([[53, 80, 67, 62],
       [50, 75,  7, 19],
       [ 8, 90, 45, 56],
       [90, 87,  8, 98]], dtype=int32)

In [5]:
# i have a index=50 ,i need to know the position in matrix.


np.argwhere(two_dim==97)

array([], shape=(0, 2), dtype=int64)

In [6]:
# question: find the position of the index 28?.

In [7]:
np.argwhere(two_dim==28)

array([], shape=(0, 2), dtype=int64)

In [8]:
# to insert a new row in position 2 and matrix is [7,12,20,18].

np.insert(two_dim,2,[7,12,20,18])

array([53, 80,  7, 12, 20, 18, 67, 62, 50, 75,  7, 19,  8, 90, 45, 56, 90,
       87,  8, 98], dtype=int32)

In [9]:
# in python,python dont know where to put the numbers since row and colum have same 2.so introduction of axis
# axis=0------------->X axis.
# axis=1------------->Y axis.

In [10]:
#question1:insert [2,34,56,78] in row position=3?.

np.insert(two_dim,3,[2,34,56,78,],axis=0)

array([[53, 80, 67, 62],
       [50, 75,  7, 19],
       [ 8, 90, 45, 56],
       [ 2, 34, 56, 78],
       [90, 87,  8, 98]], dtype=int32)

In [11]:
#question2:insert [3,5,83,99] in column position=4?.

np.insert(two_dim,4,[3,5,83,99],axis=1)

array([[53, 80, 67, 62,  3],
       [50, 75,  7, 19,  5],
       [ 8, 90, 45, 56, 83],
       [90, 87,  8, 98, 99]], dtype=int32)

In [12]:
# to delete a row matrix, ie; delete a row having position 2.
np.delete(two_dim,2,axis=0)

array([[53, 80, 67, 62],
       [50, 75,  7, 19],
       [90, 87,  8, 98]], dtype=int32)

In [13]:
# to delete a column matrix,ie; delete a column having position 3.
np.delete(two_dim,3,axis=1)

array([[53, 80, 67],
       [50, 75,  7],
       [ 8, 90, 45],
       [90, 87,  8]], dtype=int32)

In [14]:
# to see transpose of a matrix.
np.transpose(two_dim)

array([[53, 50,  8, 90],
       [80, 75, 90, 87],
       [67,  7, 45,  8],
       [62, 19, 56, 98]], dtype=int32)

In [15]:
# to see determinant of a matrix.
np.linalg.det(two_dim)

np.float64(18664081.000000015)

In [16]:
# to see inverse of a matrix.
np.linalg.inv(two_dim)

array([[ 0.01118775,  0.00780355, -0.018192  ,  0.00180454],
       [-0.00815245,  0.01328788,  0.01069905, -0.00353229],
       [ 0.02014158, -0.00485832, -0.0054682 , -0.00867602],
       [-0.00468129, -0.0185663 ,  0.00765519,  0.01239091]])

# 1. ARITHMATIC OPERATORS

In [17]:
two_dim

array([[53, 80, 67, 62],
       [50, 75,  7, 19],
       [ 8, 90, 45, 56],
       [90, 87,  8, 98]], dtype=int32)

In [18]:
a = np.random.randint(1,100,4).reshape(2,2)
a

array([[61, 93],
       [51, 41]], dtype=int32)

In [19]:
b= np.random.randint(1,100,4).reshape(2,2)
b


array([[84, 64],
       [ 7, 82]], dtype=int32)

In [20]:
# addition of array matrix
a+b

array([[145, 157],
       [ 58, 123]], dtype=int32)

In [21]:
# subtraction of array matrix
a-b

array([[-23,  29],
       [ 44, -41]], dtype=int32)

In [22]:
# multiplication of array matrix
a*b

array([[5124, 5952],
       [ 357, 3362]], dtype=int32)

In [23]:
# division of array matrix.
a/b

array([[0.72619048, 1.453125  ],
       [7.28571429, 0.5       ]])

In [24]:
# matrix multiplication
a@b

array([[ 5775, 11530],
       [ 4571,  6626]], dtype=int32)

# 2. STACKING OF ARRAYS.

## stacking is used to combine arrays. 2 methods are used.
### 1)hstack----> combining horizontally.
### 2)vstack-----> combining vertically.

In [26]:
np.hstack([a,b])

array([[61, 93, 84, 64],
       [51, 41,  7, 82]], dtype=int32)

In [27]:
np.vstack([a,b])

array([[61, 93],
       [51, 41],
       [84, 64],
       [ 7, 82]], dtype=int32)

In [29]:
# identity matrix---> having 1 and 0's. give a 2by2 matrix

np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [30]:
# identity matrix---> having 1 and 0's. give a 4by4 matrix.
np.identity(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
# question 1: create a zero  matrix having 2 rows and 3 column.

np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# question 2: create a one's matrix having 3 rows and 2 column.

np.ones(shape=(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
# to see mean of an array.
np.mean(two_dim)

np.float64(55.9375)

In [35]:
# to see sum of array.
np.sum(two_dim)

np.int64(895)

# Seeing mean,median,sum,avg of a matrix based on axis.

In [37]:
# to see mean of the rows .

np.mean(two_dim,axis=0)

array([50.25, 83.  , 31.75, 58.75])

In [38]:
# to see mean of the columns.
np.median(two_dim,axis=1)

array([64.5, 34.5, 50.5, 88.5])

In [39]:
# to see unique numbers in the array 

np.unique(two_dim)

array([ 7,  8, 19, 45, 50, 53, 56, 62, 67, 75, 80, 87, 90, 98],
      dtype=int32)