# PYTHON

# 1) ARITHMETIC OPERATORS

In [1]:
a,b,c,d,e=333,444,555,3,4
print('Addition of all numbers:',a+b+c+d)
print('Subtraction of c from d:',c-d)
print('Multiplication of all:',a*b*c*d*e)
print('Divition of a by b:',a/b)
print('Give queiont of a by b:',a//b)
print('Give Remainder of a by b:',a%b)

Addition of all numbers: 1335
Subtraction of c from d: 552
Multiplication of all: 984694320
Divition of a by b: 0.75
Give queiont of a by b: 0
Give Remainder of a by b: 333


 # 2) CONDITIONAL OPEARTORS

In [2]:
a,b=10,20
print(a==b)
print(a!=b)
print(a>b)
print(b<a)
print(a>=b)
print(a<=b)

False
True
False
False
False
True


# 3) LOGICAL OPERATORS

In [3]:
a,b=12,8
# PRINT A>10 AND B<10
# PRINT A>12 OR B>7
# PRINT not(A>10)

In [4]:
print(a>10 & b<10)
print(a>12 | b>7)
print(not(a>10))

True
False
False


# 4) UNARY OPERATORS

In [5]:
a=10
print(a+5)
print(a-5)
print(not(a))
print(~a)

15
5
False
-11


# DATA TYPES

In [6]:
a=10
b=10.5
c='WELCOME'

In [7]:
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'str'>


## BASIC STRING OPERATIONS

In [8]:
str1='weLcome homE Abhi'

In [9]:
# len()---> Gives the length of the string / number of elements in the list.
print(len(str1))

17


In [10]:
# captilize()---> convert the first character of the string to capitial.
str1.capitalize()

'Welcome home abhi'

In [11]:
# upper()---> convert the string to uppercase.
str1.upper()

'WELCOME HOME ABHI'

In [12]:
# lower()--->covert the string to lowercase.
str1.lower()

'welcome home abhi'

In [13]:
# swap()---> convert the string to upper to lower and lower to upper.
str1.swapcase()

'WElCOME HOMe aBHI'

In [14]:
# split()---> used to sepearte words in the string.
str1.split()

['weLcome', 'homE', 'Abhi']

In [15]:
# join()---> used to join the splited words.
''.join(str1)

'weLcome homE Abhi'

In [16]:
# strip---> used to remove space.
# lstrip---> used to remove left space.
# rstrip---> used to remove right space.
print(str1.lstrip())
print(str1.rsplit())
print(str1.strip())

weLcome homE Abhi
['weLcome', 'homE', 'Abhi']
weLcome homE Abhi


In [17]:
str2="Data Science"
str3="machine learning"
str4="PyThOn"
str5="Python SQL PowerBI Tableau"
str6=["Python", "SQL", "ML"]
str7="      Welcome to Python      "
# Length of the string2 ?
# Output of str2 converted to uppercase ?
# Output of str2 convert to lowercase ?
# Capitalize form of string3 ?
# Swap the string4 ?
# splited version string 5 ?
# joined form of string 6 ?
# Removed extra space of str7(left,right)?
# what is the index of 'y' in str7 ?
# show me index number of 'y' in str7 ?
# show mw the index of second 'o' in the str7 ? (hint: find the index of first'o',so i get 10 then add next starting that is 11)

In [18]:
print(len(str2))
print(str2.upper())
print(str2.lower())
print(str3.capitalize())
print(str4.swapcase())
print(str5.split())
print(''.join(str6))
print(str7.strip())
print(str7.index('y'))
print(str7.index('o',11))

12
DATA SCIENCE
data science
Machine learning
pYtHoN
['Python', 'SQL', 'PowerBI', 'Tableau']
PythonSQLML
Welcome to Python
18
15


# DATASTRUCTURES

# LIST

In [19]:
# Create a list containing five fruits and print it.
list=['apple','orange','strawberry','mulberry','banana']
print(list)

['apple', 'orange', 'strawberry', 'mulberry', 'banana']


In [20]:
# Create a list of five numbers and print the third element using indexing.
list2=[4,9,17,28,32]
print(list2[2])

17


In [21]:
# Create a list of five numbers and print the last element using negative indexing.
list3=[33,46,78,92,101]
print(list3[-1])

101


In [22]:
# Create the following list and use append() to add "Mango".
fruits1 = ['Apple','Banana','Orange']

In [23]:
# append()---> used to add a element at the end of the list.
fruits1.append('Mango')
fruits1

['Apple', 'Banana', 'Orange', 'Mango']

In [24]:
# Create the following list and use extend() to add ["SQL", "Power BI"]
skills = ["Python"]

In [25]:
# extend()---> used to add multiple elements at the end of the list.
skills.extend(['SQL','Power BI'])
skills

['Python', 'SQL', 'Power BI']

In [26]:
# Create the following list and insert 200 at index 2.
numbers = [100, 300, 400]

In [27]:
# insert()---> used to insert a element its based on indexing.
numbers.insert(2,200)
numbers

[100, 300, 200, 400]

In [28]:
# Remove "Banana" from the following list.
fruits1 = ['Apple','Banana','Orange']

In [29]:
# remove---> used to remove elements from the list.
fruits1.remove('Banana')
fruits1

['Apple', 'Orange']

In [30]:
# Remove the element at index 3.
numbers = [10, 20, 30, 40, 50]

In [31]:
# pop()---> used to remove element based on indexing. if no indexing it will remove element at last.
numbers.pop(3)
numbers

[10, 20, 30, 50]

In [32]:
# Count how many times 20 appears.
numbers = [10, 20, 30, 20, 40, 20]

In [33]:
# count()---> used to know how many.
numbers.count(20)

3

In [34]:
#Find the index of "Python".
languages = ["Java", "Python", "C++", "SQL"]

In [35]:
# index()---> used for indexing.
languages.index('Python')

1

In [36]:
languages[1]

'Python'

In [37]:
# Predict the output.
list1 = [10, 20]
list1.append([30, 40])
# answer:    list1 = [10,20,[30,40]]

In [38]:
# Predict the output.
list1 = [10, 20]
list1.extend([30, 40])
# answer:    list1 = [10,20,30,40]

In [39]:
# Predict the output.
a = [10, 20, 30, 20]
a.remove(20)
a
# answer : a= [10,30,20]

[10, 30, 20]

In [40]:
# Predict the output.
a = [10, 20, 30]
x = a.pop()
print(x)
print(a)
# answer :  print(x)---> 30, print(a)--->[10,20]

30
[10, 20]


In [41]:
# Predict the output.
a = [100, 300]
a.insert(1, 200)
print(a)
# answer :  a=[100,200,300]

[100, 200, 300]


In [42]:
# Create an empty list.
# Add 10, 20 and 30 using append().
# Print the list.
listA=[]
listA.append(10)
listA.append(20)
listA.append(30)
print(listA)
             

[10, 20, 30]


In [43]:
# Create the list [10, 20, 40].
# Insert 30 between 20 and 40.
listB=[10,20,40]
listB.insert(2,30)
listB

[10, 20, 30, 40]

In [44]:
# Remove the first occurrence of 5
numbers = [5, 10, 5, 15, 5]
numbers.pop(0)
numbers

[10, 5, 15, 5]

In [45]:
#Count how many times "Python" appears.
languages = ["Python", "Java", "Python", "SQL", "Python"]
languages.count('Python')

3

In [46]:
# Remove the last element using pop().
# Store the removed element in a variable.
# Print the removed element.
# Print the updated list.
languages = ["Python", "Java", "Python", "SQL", "Python"]
x=languages.pop(-1)
print(x)
print(languages)

Python
['Python', 'Java', 'Python', 'SQL']


# important notes: append()---->extend()---->insert(index,values)---->remove() remove element in first order when asked to delete same number who comes first will deleted.---> pop(index)--->index('')

# TUPLE

In [47]:
tuple1=(234,100,4556,4444,6736,4444,100)
print(tuple1)

(234, 100, 4556, 4444, 6736, 4444, 100)


In [48]:
# count()----> used to know how many.
tuple1.count(4444)

2

In [49]:
# index()----> used for indexing.
tuple1.index(100,2)

6

# important notes : index(value,index no)---> search 100 after index value 2
# insert---> insert(index,value)
# index----> index(value,index)

In [50]:
#Create a tuple containing the following values:
# 10, 20, 30, 40, 50
# Print the tuple.
tupleA=(10,20,30,40,50)
print(tupleA)

(10, 20, 30, 40, 50)


In [51]:
# Create the following tuple and print the third element using indexing.
numbers = (100, 200, 300, 400, 500)
numbers[2]

300

In [52]:
# Create the following tuple and print the second last element using negative indexing.
numbers = (10, 20, 30, 40, 50)
numbers[-2]

40

In [53]:
# Find how many times 20 appears in the following tuple.
numbers = (10, 20, 30, 20, 40, 20)
numbers.count(20)

3

In [54]:
# Find the index of "Python" in the following tuple.
languages = ("Java", "Python", "C++", "SQL")
languages.index('Python')

1

# SETS

In [55]:
# Create a set {10, 20, 30}.
# Add 40 using add().
# Print the updated set.
numbers={10,20,30}
numbers.add(40)
numbers

{10, 20, 30, 40}

In [56]:
# Create a set {"Python", "Java", "SQL"}.
# Remove "Java" using remove().
# Print the updated set.
lan={'python','java','sql'}
lan.remove('java')
lan

{'python', 'sql'}

In [57]:
# Create a set {1, 2, 3}.
# Create a copy of the set.
# Add 4 to the copied set.
# Print both the original and copied sets.
numbers1={1,2,3}
numbers2=numbers1.copy()
numbers2.add(4)
print(numbers1)
print(numbers2)

{1, 2, 3}
{1, 2, 3, 4}


In [58]:
# Find the union of the following sets.
A = {1, 2, 3}
B = {3, 4, 5}
A.union(B)

{1, 2, 3, 4, 5}

In [59]:
# Print both the original and copied sets.
numbers1={1,2,3}
numbers2= numbers1.copy()
# Find the intersection of the following sets.
numbers1.intersection(numbers2)

{1, 2, 3}

In [60]:
# find intersection
A = {10, 20, 30, 40}
B = {20, 40, 60}
A.intersection(B)

{20, 40}

In [61]:
# Find the difference (A - B).
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}
A.difference(B)

{1, 2}

In [62]:
# Check whether A is a subset of B.
A = {1, 2}
B = {1, 2, 3, 4}
A.issubset(B)

True

In [63]:
# Check whether B is a superset of A.
A = {10, 20}
B = {10, 20, 30, 40}
B.issuperset(A)

True

In [64]:
# Predict the Output
A = {1, 2, 3}
B = {3, 4}
print(A.union(B))
print(A.intersection(B))
# answer: A UNION B= {1,2,3,4} , A INTERSECTION B ={3}

{1, 2, 3, 4}
{3}


# DICTIONARIES

In [65]:
# Create a dictionary with the following details:
# Name = "Abhijith"
# Age = 22
# Course = "Data Science"
# Print the dictionary.
dict1={ 'Name': ['ABHIJITH K'],
        'Age': [22],
        'Course':['Datascience']}
dict1

{'Name': ['ABHIJITH K'], 'Age': [22], 'Course': ['Datascience']}

In [66]:
# print the value of Name from dict1
dict1['Name']

['ABHIJITH K']

In [67]:
# Print the value of Age from dict1.
dict1['Age']

[22]

In [68]:
# Print the value of Course from dict1.
dict1['Course']

['Datascience']

In [69]:
# Add a new key City with the value Kannur
dict1['City']='Kannur'
print(dict1)

{'Name': ['ABHIJITH K'], 'Age': [22], 'Course': ['Datascience'], 'City': 'Kannur'}


In [70]:
# Change the value of Age from 22 to 23
dict1['Age']=23
dict1

{'Name': ['ABHIJITH K'],
 'Age': 23,
 'Course': ['Datascience'],
 'City': 'Kannur'}

In [71]:
# Change the value of Course from Datascience to Data Analytics.
dict1['Course']='Data Analytics'
dict1

{'Name': ['ABHIJITH K'],
 'Age': 23,
 'Course': 'Data Analytics',
 'City': 'Kannur'}

In [1]:
# operations learned: 
#                      1) create---> { }
#                      2) access---> dict1[]
#                      3) add------> dict1['new_keys']='new_value' , dict1.setdefault('new_key',['new_value']
#                      4) update---->dict1['existing_key']='new_value'
#                      5) change---->dict1['key'][index]='new_value'

In [2]:
dict2 ={ 'Names':['abi','akku','appu','kuttan'],
         'Age':[22,18,23,23],
         'Place':['BANGLORE','KOCHIN','PUNE','DELHI']}
print(dict2)

{'Names': ['abi', 'akku', 'appu', 'kuttan'], 'Age': [22, 18, 23, 23], 'Place': ['BANGLORE', 'KOCHIN', 'PUNE', 'DELHI']}


In [3]:
# Print all names.
dict2['Names']

['abi', 'akku', 'appu', 'kuttan']

In [4]:
# Print the first name.
dict2['Names'][0]

'abi'

In [5]:
# Add Course with the value Data Science.
dict2['Course']='Data science'
dict2

{'Names': ['abi', 'akku', 'appu', 'kuttan'],
 'Age': [22, 18, 23, 23],
 'Place': ['BANGLORE', 'KOCHIN', 'PUNE', 'DELHI'],
 'Course': 'Data science'}

In [6]:
# Add Salary with values [25000, 30000, 35000, 40000]
dict2['Salary']=  [25000, 30000, 35000, 40000]
dict2

{'Names': ['abi', 'akku', 'appu', 'kuttan'],
 'Age': [22, 18, 23, 23],
 'Place': ['BANGLORE', 'KOCHIN', 'PUNE', 'DELHI'],
 'Course': 'Data science',
 'Salary': [25000, 30000, 35000, 40000]}

In [7]:
# Change PUNE to MUMBAI.
dict2['Place'][2]='MUMBAI'
dict2

{'Names': ['abi', 'akku', 'appu', 'kuttan'],
 'Age': [22, 18, 23, 23],
 'Place': ['BANGLORE', 'KOCHIN', 'MUMBAI', 'DELHI'],
 'Course': 'Data science',
 'Salary': [25000, 30000, 35000, 40000]}

In [8]:
# Change all ages
dict2['Age']=['23,33,44,55']
dict2

{'Names': ['abi', 'akku', 'appu', 'kuttan'],
 'Age': ['23,33,44,55'],
 'Place': ['BANGLORE', 'KOCHIN', 'MUMBAI', 'DELHI'],
 'Course': 'Data science',
 'Salary': [25000, 30000, 35000, 40000]}

In [9]:
# keys()----> gives keys.
# Print all dictionary keys.
dict2.keys()

dict_keys(['Names', 'Age', 'Place', 'Course', 'Salary'])

In [10]:
# values()---> gives values
# Print all dictionary values.
dict2.values()

dict_values([['abi', 'akku', 'appu', 'kuttan'], ['23,33,44,55'], ['BANGLORE', 'KOCHIN', 'MUMBAI', 'DELHI'], 'Data science', [25000, 30000, 35000, 40000]])

In [11]:
# get()---> used to get specified keyvalue.
# Get the Names list using get()
dict2.get('Names')

['abi', 'akku', 'appu', 'kuttan']

In [12]:
# item()---> used to give keyvalue pairs.
dict2.items()

dict_items([('Names', ['abi', 'akku', 'appu', 'kuttan']), ('Age', ['23,33,44,55']), ('Place', ['BANGLORE', 'KOCHIN', 'MUMBAI', 'DELHI']), ('Course', 'Data science'), ('Salary', [25000, 30000, 35000, 40000])])

In [13]:
dict3 = {
    'Name': ['Abi', 'Akku', 'Appu'],
    'Age': [22, 18, 23],
    'Place': ['Bangalore', 'Kochi', 'Pune']
}

In [14]:
# How would you print Appu's place?
dict3['Place'][2]

'Pune'

In [15]:
dictA = {
    'Name': ['Abi', 'Akku', 'Appu', 'Kuttan'],
    'Age': [22, 18, 23, 23],
    'Place': ['Bangalore', 'Kochi', 'Pune', 'Delhi']
}

In [16]:
# Write Python code to print Akku's age.
dictA['Age'][1]

18

# CONDITION

### TASK 1: find a number is +ve,-ve,0

In [18]:
x=-2
if x>0:
    print('positive')
elif x<0:
    print('negative')
else:
    print('zero')

negative


### TASK 2: Check the number is even or odd

In [21]:
x=5
if x%2==0:
    print('number is even')
else:
    print('number is odd')


number is odd


### TASK 3: Create a list of numbers and check the numbers in the list is odd or even

In [23]:
abi=[1,2,3,4,5,6,7,8,9,10]
for i in abi:
    if i%2==0:
        print('number is odd',i)
    else:
        print('number is even',i)

number is even 1
number is odd 2
number is even 3
number is odd 4
number is even 5
number is odd 6
number is even 7
number is odd 8
number is even 9
number is odd 10


### TASK 4:Create a list and check the numbers in the list is odd or even and print seperatly and store seperatly

In [26]:
abi=[1,2,3,4,5,6,7,8,9,10]
even_list=[]
odd_list=[]
for i in abi:
    if i%2==0:
        even_list.append(i)
    else:
        odd_list.append(i)
print('even numbers',even_list)
print('odd numbers',odd_list)

even numbers [2, 4, 6, 8, 10]
odd numbers [1, 3, 5, 7, 9]


### TASK 5: Create a list of numbers and Separate positive numbers,Separate negative numbers,Print them in two different lists

In [28]:
abi=[0,-1,2,-3,4,5,6,-7,8,9,-10]
positive_list=[]
negative_list=[]
for i in abi:
    if i>=0:
        positive_list.append(i)
    else:
        negative_list.append(i)
print('positive numbers',positive_list)
print('negative numbers',negative_list)

positive numbers [0, 2, 4, 5, 6, 8, 9]
negative numbers [-1, -3, -7, -10]


### TASK 6: Create a list of numbers and,Separate numbers divisible by 3,Separate numbers divisible by 5,Separate numbers divisible by both 3 and 5,Store remaining numbers in another list

In [30]:
abi=[2,45,333,8,5,77,15,90]
div3=[]
div5=[]
div35=[]
num=[]
for i in abi:
    if i%3==0 & i%5==0:
        div35.append(i)
    elif i%3==0:
        div3.append(i)
    elif i%5==0:
        div5.append(i)
    else:
        num.append(i)
print('Divisible by both 3 and 5',div35)
print('Divisible by 3',div3)
print('Divisible by 5',div5)
print('Not in any',num)

Divisible by both 3 na d 5 [45, 333, 15, 90]
Divisible by 3 []
Divisible by 5 [5]
Not in any [2, 8, 77]


### TASK 7: Check a student's grade:
# 90 or above  → A
# 75 to 89     → B
# 50 to 74     → C
# Below 50     → Fail
# -------------------------
# marks = 82

In [49]:
x = 45

if x >= 90:
    print('A Grade')
elif x >= 75 and x <= 89:
    print('B GRADE')
elif x >= 50 and x <= 74:
    print('C GRADE')
elif x < 50:
    print('FAIL')
else:
    print('Not Attended')

FAIL


### TASK 8: Find the largest number among these three
# a = 25
# b = 40
# c = 15

In [50]:
a,b,c=25,40,15
if a>b and a>c:
    print('A is larger:',a)
elif b>a and b>c:
    print('B is larger',b)
else:
    print ('C is larger',c)


B is larger 40


### TASK 9: INTERVIEW LEVEL
# marks=82
# attendance = 68
### Marks ≥ 75 and attendance ≥ 75 → "Eligible for Interview"
### Marks ≥ 75 but attendance < 75 → "Low Attendance"
### Marks < 75 → "Marks Too Low"

In [51]:
marks=82
attendance=68
if marks>=75 and attendance>=75:
    print('Eligible for Interview')
elif marks>=75 and attendance<75:
    print('Low attendence')
elif marks< 75:
    print('Marks too low')
else:
    print('DONT ATTENT INTERVIEW')
    

Low attendence


# FUNCTIONS

# def function

In [ ]:
def add(x):
    return x+x

In [53]:
add(3)

6

In [54]:
def mul(x,y):
    return x+3,y+4

In [55]:
mul(2,4)

(5, 8)

### TASK 1: Factorial of a number 

In [61]:
import math

In [63]:
def factorial_of_a_number(x):
    return math.factorial(x)
factorial_of_a_number(5)  

120

### TASK 2: Use function to find the number is odd or even

In [65]:
def oddoreven(x):
    if x%2==0:
        print('even')
    else:
        print('odd')
        return(x)
oddoreven(3)       

odd


3

### TASK 3: Create a function called greet() that prints 'Hello, Welcome to Python'

In [71]:
def greet():
    print('Hello, Welcome to Python',)
greet()

Hello, Welcome to Python


### TASK 4: Create a function called cube() that takes one number and prints its cube.

In [73]:
def cube(x):
    return x**3
cube(2)    

8

### TASK 5: Create a function called check_number() that takes a number and prints:
# Positive → "Positive"
# Negative → "Negative"
# Zero → "Zero"

In [79]:
def check_numbers(x):
    if x>0:
        print('positive')
    elif x<0:
        print('negative')
    else:
        print('zero')
        return(x)
check_numbers(-1)        

negative


### TASK 4: Create a function called largest() that takes two numbers and prints which number is larger.

In [81]:
def largest(x,y):
    if x>y:
        print('x is largest')
        return (x)
    else:
        print('y is largest')
        return(y)
largest(3,4)        

y is largest


4

# lambda

In [1]:
add= lambda x: x+4
add(2)

6

In [2]:
multi=lambda x:x*9
multi(3)

27

# ARRAY

# 1D ARRAY

In [3]:
# create a one dimentional array
import numpy as np
one_dim=np.array([3,45,67,89,9,43])
one_dim

array([ 3, 45, 67, 89,  9, 43])

In [4]:
# type of array
type(one_dim)

numpy.ndarray

In [6]:
# np.where()----> to find position wich means it gives index position.
np.where(one_dim==67)

(array([2]),)

In [7]:
#np.insert()----> to insert a element based on indexing.
np.insert(one_dim,2,100)

array([  3,  45, 100,  67,  89,   9,  43])

In [8]:
#np.delete()----> used to remove element.
np.delete(one_dim,2)

array([ 3, 45, 89,  9, 43])

In [9]:
# max()---> to find maximum in a array.
np.max(one_dim)

np.int64(89)

In [10]:
# min()---> to find minimum in a array.
np.min(one_dim)

np.int64(3)

In [11]:
# mean()---> to find the avearge of array.
np.mean(one_dim)

np.float64(42.666666666666664)

In [12]:
# median()---> to find the mid value data.
np.median(one_dim)

np.float64(44.0)

In [13]:
# unique()---> to find non duplictaes/ unique elemnts.
np.unique(one_dim)

array([ 3,  9, 43, 45, 67, 89])

In [14]:
# argmin()---> gives the index of the smaller number in the array.
np.argmin(one_dim)

np.int64(0)

In [15]:
# argmax()---> gives the index of largest number in the array.
np.argmax(one_dim)

np.int64(3)

In [16]:
# arange()---> to create a array by using range.
np.arange(1,4)

array([1, 2, 3])

In [24]:
# create an array and perfom following.
# access the 3rd element and gives the value.
# acess position 3 to 7
# add +5 with every element
# show only elemnts greater than 34.
arr=np.array([3,6,8,10,17,19,34,99,101,30])
print(arr[2])
print(arr[3:7])
print(arr+5)
print(arr[arr>34])

8
[10 17 19 34]
[  8  11  13  15  22  24  39 104 106  35]
[ 99 101]


In [26]:
arr1 = np.array([12, 25, 8, 40, 15, 30])
# 1)Print the second and fifth elements using indexing.
print(arr1[1])
print(arr1[4])

25
15


In [31]:
# 2)Using the same array, print from : [25, 8, 40]
print(arr1[1:4])

[25  8 40]


In [33]:
# 3)Add 10 to every element of the array. Expected: [22 35 18 50 25 40]
print(arr1+10)

[22 35 18 50 25 40]


In [35]:
# 4)Print only the values that are greater than 20
arr1[arr1>20]

array([25, 40, 30])

In [42]:
# 5)marks = np.array([45, 78, 92, 35, 88, 60])
# Average marks
# Highest mark
# Lowest mark
# Number of students who scored 60 or above
marks = np.array([45, 78, 92, 35, 88, 60])
print(np.average(marks))
print(np.max(marks))
print(np.min(marks))
print(np.sum(marks >=60))

66.33333333333333
92
35
4


# 2D ARRAY

In [47]:
# create a 2d array
arrr=np.array([[10,20,30],[40,50,60],[70,80,90]])
arrr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [49]:
# access the 50 using indexing.
arrr[1,1]

np.int64(50)

In [50]:
# print the value 30 using indexing
arrr[0,2]

np.int64(30)

In [51]:
# print first row
arrr[0]

array([10, 20, 30])

In [52]:
# print first column.
arrr[:,0]

array([10, 40, 70])

In [53]:
# print second row
arrr[1]

array([40, 50, 60])

In [54]:
# print second column
arrr[:,1]

array([20, 50, 80])

In [55]:
# add 10 to every value
arrr+10

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [56]:
# sum of all values.
np.sum(arrr)

np.int64(450)

In [57]:
# sum of rows----> axis=1
np.sum(arrr,axis=1)

array([120, 150, 180])

In [58]:
#sum of columns---> axis=0
np.sum(arrr,axis=0)

array([120, 150, 180])

In [60]:
# mean of rows
np.mean(arrr,axis=1)

array([20., 50., 80.])

In [61]:
# mean of column.
np.mean(arrr,axis=0)

array([40., 50., 60.])

In [74]:
#TASK 1
arr5 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]])
# Find the sum of each column.
# Find the sum of each row.
# Find the average of each row.
# Find the maximum value from each row.
# Find the minimum value from each column.
print(np.sum(arr5,axis=0))
print(np.sum(arr5,axis=1))
print(np.average(arr5,axis=1))
print(np.max(arr5,axis=1))
print(np.min(arr5,axis=0))

[120 150 180]
[ 60 150 240]
[20. 50. 80.]
[30 60 90]
[10 20 30]


In [76]:
# Find the average of each column
arr6= np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(np.average(arr6,axis=0))

[40. 50. 60.]


In [78]:
# Find the sum of each row
arr7= np.array([
    [15, 20, 25],
    [30, 35, 40],
    [45, 50, 55]
])
print(np.sum(arr7,axis=1))

[ 60 105 150]


In [81]:
# Reshape this array into 3 rows and 2 columns.
arr8= np.array([10, 20, 30, 40, 50, 60])
print(np.reshape(arr8,(3,2)))

[[10 20]
 [30 40]
 [50 60]]


In [83]:
# Reshape it into 4 rows and 3 columns.
arr9= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(np.reshape(arr9,(4,3)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [85]:
# create a random array
arrrr=np.random.randint(1,100,16).reshape(4,4)
arrrr


array([[89, 65, 31, 23],
       [23, 90, 42, 80],
       [92, 36, 14, 44],
       [95, 50, 57, 12]], dtype=int32)

In [88]:
# insert this column [33,33,33,33] at index 2 in arr
print(np.insert(arrrr,2,[33,33,33,33],axis=0))

[[89 65 31 23]
 [23 90 42 80]
 [33 33 33 33]
 [92 36 14 44]
 [95 50 57 12]]


In [91]:
# delete the same column inserted
np.delete(arrrr,2,axis=0)

array([[89, 65, 31, 23],
       [23, 90, 42, 80],
       [95, 50, 57, 12]], dtype=int32)

In [92]:
# transpose of the array
np.transpose(arrrr)

array([[89, 23, 92, 95],
       [65, 90, 36, 50],
       [31, 42, 14, 57],
       [23, 80, 44, 12]], dtype=int32)

In [93]:
# determinant of array
np.linalg.det(arrrr)

np.float64(-11265607.999999998)

In [94]:
# inverse of array
np.linalg.inv(arrrr)

array([[ 0.00250177, -0.00587594,  0.00918104,  0.00071403],
       [ 0.03448478,  0.00203114, -0.01735876, -0.01598795],
       [-0.02934382,  0.00618946, -0.00408145,  0.02994459],
       [-0.02410913,  0.00865484,  0.01903182,  0.00206025]])

# GPT MOCK

In [15]:
numbers = [10, 25, 7, 40, 15]
largest=numbers[0]
for i in numbers:
    if i>largest:
        largest=i
print(largest)   

40
