# 1) SIMPLE LINEAR REGRESSION

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df=pd.read_csv('SL1.csv')
df

,Area,Price
0,2600,550000
1,3000,565000
2,3200,610000
3,3600,680000
4,4000,725000


In [13]:
df.shape

(5, 2)

## Seperate the target from fetures.

In [15]:
target=df[['Price']]
target

,Price
0,550000
1,565000
2,610000
3,680000
4,725000


## Or use this method

In [16]:
features=df.drop(columns=['Price'])
features

,Area
0,2600
1,3000
2,3200
3,3600
4,4000


### import the 1st package for train_test_split

In [17]:
e= sklearn.model_selection import train_test_split

### import the second package for model

In [ ]:
from sklearn.linear_model import LinearRegression

### setting variables and checking rows and columns

In [20]:
x_train,x_test,y_train,y_test= train_test_split(features,target,train_size=0.7,random_state=10)
print(x_train.shape)
print(y_train.shape)
print(y_train.shape)
print(y_test.shape)

(3, 1)
(3, 1)
(3, 1)
(2, 1)


### model training

In [33]:
lin_reg=LinearRegression()
lin_reg.fit(x_train,y_train)

LinearRegression()

In [29]:
b0=lin_reg.intercept_
b0

array([191794.87179487])

In [30]:
b1=lin_reg.coef_
b1

array([[131.73076923]])

In [32]:
# training validation
y_predict_tr=lin_reg.predict(x_train)
y_predict_tr

array([[534294.87179487],
       [718717.94871795],
       [586987.17948718]])

In [35]:
# testing validation
y_predict_te=lin_reg.predict(x_test)
y_predict_te

array([[613333.33333333],
       [666025.64102564]])

### R_Square

In [36]:
from sklearn.metrics import r2_score

In [39]:
# training validation
y_predict_tr=lin_reg.predict(x_train)
y_predict_tr
r2_score(y_train,y_predict_tr)

y_predict_tr=lin_reg.predict(x_train)


0.9591026776589222

In [41]:
# testing validation
y_predict_te=lin_reg.predict(x_test)
y_predict_te
r2_score(y_test,y_predict_te)

0.9157576245488329